### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wtn2002** [Vitruves/carquet#10]
I got this error when I try to build follow your example.

[root@xxx build]# cmake .. -DCMAKE_BUILD_TYPE=Release -DCARQUET_BUILD_SHARED=ON
-- Found system libzstd
-- Found system zlib: 1.2.11
-- OpenMP found - enabling parallel column reading
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /opt/carquet-main/build
[root@xxx build]# make -j 4
[  1%] Building C object CMakeFiles/carquet.dir/src/simd/x86/avx512_ops.c.o
/opt/carquet-main/src/simd/x86/avx512_ops.c: In function ‘carquet_avx512_byte_stream_split_encode_float’:
/opt/carquet-main/src/simd/x86/avx512_ops.c:148:37: warning: implicit declaration of function ‘_mm512_set_epi8’; did you mean ‘_mm512_set1_epi8’? [-Wimplicit-function-declaration]
     const __m512i intra_lane_shuf = _mm512_set_epi8(
                                     ^~~~~~~~~~~~~~~
                                     _mm512_set1_epi8
/opt/carquet-main/src/simd/x86/avx512_ops.c:148:37: error: incompatible types when initializing type ‘__m512i’ {aka ‘const __vector(8) long long int’} using type ‘int’
make[2]: *** [CMakeFiles/carquet.dir/build.make:636: CMakeFiles/carquet.dir/src/simd/x86/avx512_ops.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/carquet.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
[root@xxx build]#

my system is RedHat 8.10

**Comment by Vitruves** [comment]
Thanks for the report! Both issues are fixed on main and will ship in **v0.3.0** (I will commit at the same time I post this reply).

Issue 1 — AVX-512 compiles even with -DCARQUET_ENABLE_AVX512=OFF: The CMake was unconditionally compiling all SIMD source files on x86 regardless of the enable flags — the flags only controlled #defines, not source inclusion. Now each SIMD file is only compiled when its corresponding flag is ON. Additionally, CMake now auto-detects whether the compiler actually supports _mm512_set_epi8 (GCC < 9 doesn't) and disables AVX-512 automatically with a warning if it fails.

Issue 2 — undefined reference to 'log' with shared library + GCC 14: The math library (-lm) was linked as PRIVATE to the shared library. On RHEL with --no-copy-dt-needed-entries (the default), this doesn't propagate to consumers. Changed to PUBLIC so test executables linking against libcarquet.so also get -lm.

Separately, when building shared (-DCARQUET_BUILD_SHARED=ON), the dependency lookup now prefers shared versions of zstd/lz4 to avoid -fPIC issues with static libraries.

Both configurations should now work:

```
# GCC 8.5 (AVX-512 auto-disabled)
cmake .. -DCMAKE_BUILD_TYPE=Release -DCARQUET_BUILD_SHARED=ON
```

```
# GCC 14
cmake .. -DCMAKE_BUILD_TYPE=Release -DCARQUET_BUILD_SHARED=ON
```

Let me know if you hit anything else. Also note the examples were trimmed/simplified in this release — unrelated to your issue but worth mentioning in case you were referencing those files.

**Comment by wtn2002** [comment]
`cmake .. -DCMAKE_BUILD_TYPE=Release -DCARQUET_BUILD_SHARED=ON`

It work fine on Redhat 8.10 with GCC8 / GCC 11 / GCC13 / GCC14.
Thank you very much.
